#ifndef UBOLT_SN_LQN_TABLE_HPP
#define UBOLT_SN_LQN_TABLE_HPP

// GENERATED BY src/sn_lqn_table.py - DO NOT EDIT, REGENERATE INSTEAD
//
// The level-symmetric (LQn) quadrature constants for even SN orders
// 2 to 18, derived from the even axis moments through order N at
// 60 decimal digits and rounded to double here. The script's docstring
// has the derivation and the assertions.
//
// A level-symmetric set of order N has N/2 levels of direction cosine,
// with mu_i^2 in arithmetic progression. One octant holds the points
// (mu_i, mu_j, mu_k) for every ORDERED index triple with i + j + k =
// N/2 + 2 - the condition that makes the direction a unit vector - and a
// point's weight depends only on the SORTED triple, so the set looks the
// same from every axis. The other seven octants are the sign flips, and
// 2D folds the xi > 0 half onto the xi < 0 one by doubling the weights.
//
// The points are listed in LEXICOGRAPHIC triple order, which is what
// makes S4 come out as (1,1,2), (1,2,1), (2,1,1) - the base-point order
// the quadrature classes have used since they were S2/S4 literals.
//
// Never include this from include/ubolt/ - it is a src/ implementation
// detail, the same rule the vendored JSON parser follows.
//
// order | levels | points/octant | weight freedom | smallest weight | mixed-moment error | axis moments at double
//    S2 |      1 |             1 |              0 |       1.250e-01 |           0.00e+00 |               1.16e-16
//    S4 |      2 |             3 |              0 |       4.167e-02 |           0.00e+00 |               1.03e-16
//    S6 |      3 |             6 |              0 |       1.965e-02 |           3.11e-61 |               1.67e-16
//    S8 |      4 |            10 |              0 |       1.134e-02 |           3.89e-61 |               2.40e-16
//   S10 |      5 |            15 |              0 |       5.630e-03 |           8.63e-60 |               2.20e-16
//   S12 |      6 |            21 |              0 |       3.231e-03 |           9.95e-05 |               4.10e-16
//   S14 |      7 |            28 |              1 |       1.034e-03 |           5.64e-59 |               7.25e-16
//   S16 |      8 |            36 |              1 |       1.297e-03 |           2.61e-05 |               8.66e-17
//   S18 |      9 |            45 |              2 |       1.425e-05 |           2.15e-06 |               1.55e-16
//
// 'weight freedom' is the dimension of the family of sets satisfying
// every axis moment through N. Where it is non-zero the member chosen is
// the one minimising the error in the MIXED even moments
// <mu^2a eta^2b xi^2c> of total degree <= N, which the axis moments do
// not imply; that error is reported here, not required. 'smallest weight'
// is a fraction of the whole sphere and has to be positive - which is
// exactly why the table stops where it does:
//
//   S20 is NOT here because its smallest weight is -1.775e-05.
//
// That is the level-symmetric family running out rather than anything to
// work around, and it is the well-known reason SN codes cap LQn around
// here. A higher order needs a DIFFERENT family - a product or
// Gauss-Chebyshev set - not a different way of choosing within this one.
// Worst axis-moment residual over every order, at double: 7.25e-16

#include <petscsys.h>

namespace ubolt_lqn {

// One point of the principal octant: the 1-based level indices of its
// three cosines, and its weight as a fraction of the WHOLE sphere (so
// the weights of all 8 * n_points ordinates sum to 1). The consumers
// scale that by 4 pi, and 2D by another factor of 2 for the fold
struct LqnPoint {
   PetscInt  i, j, k;
   PetscReal weight;
};

// One order's table: the level cosines, then the octant points
struct LqnOrder {
   PetscInt         sn_order;
   PetscInt         n_levels;
   PetscInt         n_points;
   const PetscReal *mu;
   const LqnPoint  *points;
};

// S2: 1 level(s), 1 points per octant, 1 distinct weight(s)
static const PetscReal lqn_mu_s2[1] = {
   0.5773502691896257,
};
static const LqnPoint lqn_points_s2[1] = {
   {1, 1, 1, 0.125},
};

// S4: 2 level(s), 3 points per octant, 1 distinct weight(s)
static const PetscReal lqn_mu_s4[2] = {
   0.3500211745815407,
   0.8688903007222012,
};
static const LqnPoint lqn_points_s4[3] = {
   {1, 1, 2, 0.041666666666666664},
   {1, 2, 1, 0.041666666666666664},
   {2, 1, 1, 0.041666666666666664},
};

// S6: 3 level(s), 6 points per octant, 2 distinct weight(s)
static const PetscReal lqn_mu_s6[3] = {
   0.26663540151670473,
   0.6815077265365469,
   0.9261809355174891,
};
static const LqnPoint lqn_points_s6[6] = {
   {1, 1, 3, 0.02201576635792293},
   {1, 2, 2, 0.019650900308743738},
   {1, 3, 1, 0.02201576635792293},
   {2, 1, 2, 0.019650900308743738},
   {2, 2, 1, 0.019650900308743738},
   {3, 1, 1, 0.02201576635792293},
};

// S8: 4 level(s), 10 points per octant, 3 distinct weight(s)
static const PetscReal lqn_mu_s8[4] = {
   0.2182178902359924,
   0.5773502691896257,
   0.7867957924694432,
   0.9511897312113419,
};
static const LqnPoint lqn_points_s8[10] = {
   {1, 1, 4, 0.015123456790123457},
   {1, 2, 3, 0.011342592592592593},
   {1, 3, 2, 0.011342592592592593},
   {1, 4, 1, 0.015123456790123457},
   {2, 1, 3, 0.011342592592592593},
   {2, 2, 2, 0.011574074074074073},
   {2, 3, 1, 0.011342592592592593},
   {3, 1, 2, 0.011342592592592593},
   {3, 2, 1, 0.011342592592592593},
   {4, 1, 1, 0.015123456790123457},
};

// S10: 5 level(s), 15 points per octant, 4 distinct weight(s)
static const PetscReal lqn_mu_s10[5] = {
   0.18932132647801048,
   0.5088817555826189,
   0.6943188875943843,
   0.8397599622366848,
   0.9634909811104685,
};
static const LqnPoint lqn_points_s10[15] = {
   {1, 1, 5, 0.01116289349804459},
   {1, 2, 4, 0.009066143964045691},
   {1, 3, 3, 0.00563047092955108},
   {1, 4, 2, 0.009066143964045691},
   {1, 5, 1, 0.01116289349804459},
   {2, 1, 4, 0.009066143964045691},
   {2, 2, 3, 0.006741014310979615},
   {2, 3, 2, 0.006741014310979615},
   {2, 4, 1, 0.009066143964045691},
   {3, 1, 3, 0.00563047092955108},
   {3, 2, 2, 0.006741014310979615},
   {3, 3, 1, 0.00563047092955108},
   {4, 1, 2, 0.009066143964045691},
   {4, 2, 1, 0.009066143964045691},
   {5, 1, 1, 0.01116289349804459},
};

// S12: 6 level(s), 21 points per octant, 5 distinct weight(s)
static const PetscReal lqn_mu_s12[6] = {
   0.16721265282271328,
   0.4595476346425947,
   0.6280190966421308,
   0.760021014833664,
   0.8722705430257215,
   0.9716377192513583,
};
static const LqnPoint lqn_points_s12[21] = {
   {1, 1, 6, 0.008845323746261381},
   {1, 2, 5, 0.006985137695611101},
   {1, 3, 4, 0.004667209219853573},
   {1, 4, 3, 0.004667209219853573},
   {1, 5, 2, 0.006985137695611101},
   {1, 6, 1, 0.008845323746261381},
   {2, 1, 5, 0.006985137695611101},
   {2, 2, 4, 0.0062852376325071395},
   {2, 3, 3, 0.0032314114569687987},
   {2, 4, 2, 0.0062852376325071395},
   {2, 5, 1, 0.006985137695611101},
   {3, 1, 4, 0.004667209219853573},
   {3, 2, 3, 0.0032314114569687987},
   {3, 3, 2, 0.0032314114569687987},
   {3, 4, 1, 0.004667209219853573},
   {4, 1, 3, 0.004667209219853573},
   {4, 2, 2, 0.0062852376325071395},
   {4, 3, 1, 0.004667209219853573},
   {5, 1, 2, 0.006985137695611101},
   {5, 2, 1, 0.006985137695611101},
   {6, 1, 1, 0.008845323746261381},
};

// S14: 7 level(s), 28 points per octant, 7 distinct weight(s)
static const PetscReal lqn_mu_s14[7] = {
   0.1519858614610319,
   0.422156982304797,
   0.5773502691896257,
   0.6988920867759013,
   0.8022262552314121,
   0.8936910988743568,
   0.9766271529257704,
};
static const LqnPoint lqn_points_s14[28] = {
   {1, 1, 7, 0.007249630112124625},
   {1, 2, 6, 0.006112599704601311},
   {1, 3, 5, 0.002849191780148406},
   {1, 4, 4, 0.004926650074375979},
   {1, 5, 3, 0.002849191780148406},
   {1, 6, 2, 0.006112599704601311},
   {1, 7, 1, 0.007249630112124625},
   {2, 1, 6, 0.006112599704601311},
   {2, 2, 5, 0.004762385768001522},
   {2, 3, 4, 0.0032299259552362515},
   {2, 4, 3, 0.0032299259552362515},
   {2, 5, 2, 0.004762385768001522},
   {2, 6, 1, 0.006112599704601311},
   {3, 1, 5, 0.002849191780148406},
   {3, 2, 4, 0.0032299259552362515},
   {3, 3, 3, 0.001033697496577816},
   {3, 4, 2, 0.0032299259552362515},
   {3, 5, 1, 0.002849191780148406},
   {4, 1, 4, 0.004926650074375979},
   {4, 2, 3, 0.0032299259552362515},
   {4, 3, 2, 0.0032299259552362515},
   {4, 4, 1, 0.004926650074375979},
   {5, 1, 3, 0.002849191780148406},
   {5, 2, 2, 0.004762385768001522},
   {5, 3, 1, 0.002849191780148406},
   {6, 1, 2, 0.006112599704601311},
   {6, 2, 1, 0.006112599704601311},
   {7, 1, 1, 0.007249630112124625},
};

// S16: 8 level(s), 36 points per octant, 8 distinct weight(s)
static const PetscReal lqn_mu_s16[8] = {
   0.13895687506778034,
   0.3922892614448117,
   0.5370965613008791,
   0.6504264506287718,
   0.7467505736146811,
   0.8319965569100441,
   0.9092855009437253,
   0.9805008790117399,
};
static const LqnPoint lqn_points_s16[36] = {
   {1, 1, 8, 0.006123404894754817},
   {1, 2, 7, 0.005166199733730503},
   {1, 3, 6, 0.0025379423568134825},
   {1, 4, 5, 0.0033187172082758992},
   {1, 5, 4, 0.0033187172082758992},
   {1, 6, 3, 0.0025379423568134825},
   {1, 7, 2, 0.005166199733730503},
   {1, 8, 1, 0.006123404894754817},
   {2, 1, 7, 0.005166199733730503},
   {2, 2, 6, 0.004738345570664387},
   {2, 3, 5, 0.0016912303617272857},
   {2, 4, 4, 0.004079701679121296},
   {2, 5, 3, 0.0016912303617272857},
   {2, 6, 2, 0.004738345570664387},
   {2, 7, 1, 0.005166199733730503},
   {3, 1, 6, 0.0025379423568134825},
   {3, 2, 5, 0.0016912303617272857},
   {3, 3, 4, 0.001297035201031826},
   {3, 4, 3, 0.001297035201031826},
   {3, 5, 2, 0.0016912303617272857},
   {3, 6, 1, 0.0025379423568134825},
   {4, 1, 5, 0.0033187172082758992},
   {4, 2, 4, 0.004079701679121296},
   {4, 3, 3, 0.001297035201031826},
   {4, 4, 2, 0.004079701679121296},
   {4, 5, 1, 0.0033187172082758992},
   {5, 1, 4, 0.0033187172082758992},
   {5, 2, 3, 0.0016912303617272857},
   {5, 3, 2, 0.0016912303617272857},
   {5, 4, 1, 0.0033187172082758992},
   {6, 1, 3, 0.0025379423568134825},
   {6, 2, 2, 0.004738345570664387},
   {6, 3, 1, 0.0025379423568134825},
   {7, 1, 2, 0.005166199733730503},
   {7, 2, 1, 0.005166199733730503},
   {8, 1, 1, 0.006123404894754817},
};

// S18: 9 level(s), 45 points per octant, 10 distinct weight(s)
static const PetscReal lqn_mu_s18[9] = {
   0.12934450454592483,
   0.3680438160533936,
   0.5041651517251641,
   0.6106625499348811,
   0.7011668842521619,
   0.7812561994959132,
   0.8538662066914884,
   0.920768021061019,
   0.9831276612360871,
};
static const LqnPoint lqn_points_s18[45] = {
   {1, 1, 9, 0.005283080610547772},
   {1, 2, 8, 0.004701593422841019},
   {1, 3, 7, 0.0015335912884171478},
   {1, 4, 6, 0.004052517082162292},
   {1, 5, 5, 0.0008303241320204868},
   {1, 6, 4, 0.004052517082162292},
   {1, 7, 3, 0.0015335912884171478},
   {1, 8, 2, 0.004701593422841019},
   {1, 9, 1, 0.005283080610547772},
   {2, 1, 8, 0.004701593422841019},
   {2, 2, 7, 0.003901274194557745},
   {2, 3, 6, 0.0020014279834721493},
   {2, 4, 5, 0.002506118902433412},
   {2, 5, 4, 0.002506118902433412},
   {2, 6, 3, 0.0020014279834721493},
   {2, 7, 2, 0.003901274194557745},
   {2, 8, 1, 0.004701593422841019},
   {3, 1, 7, 0.0015335912884171478},
   {3, 2, 6, 0.0020014279834721493},
   {3, 3, 5, 1.4251525611663243e-05},
   {3, 4, 4, 0.00204723884527696},
   {3, 5, 3, 1.4251525611663243e-05},
   {3, 6, 2, 0.0020014279834721493},
   {3, 7, 1, 0.0015335912884171478},
   {4, 1, 6, 0.004052517082162292},
   {4, 2, 5, 0.002506118902433412},
   {4, 3, 4, 0.00204723884527696},
   {4, 4, 3, 0.00204723884527696},
   {4, 5, 2, 0.002506118902433412},
   {4, 6, 1, 0.004052517082162292},
   {5, 1, 5, 0.0008303241320204868},
   {5, 2, 4, 0.002506118902433412},
   {5, 3, 3, 1.4251525611663243e-05},
   {5, 4, 2, 0.002506118902433412},
   {5, 5, 1, 0.0008303241320204868},
   {6, 1, 4, 0.004052517082162292},
   {6, 2, 3, 0.0020014279834721493},
   {6, 3, 2, 0.0020014279834721493},
   {6, 4, 1, 0.004052517082162292},
   {7, 1, 3, 0.0015335912884171478},
   {7, 2, 2, 0.003901274194557745},
   {7, 3, 1, 0.0015335912884171478},
   {8, 1, 2, 0.004701593422841019},
   {8, 2, 1, 0.004701593422841019},
   {9, 1, 1, 0.005283080610547772},
};

static const PetscInt lqn_n_orders = 9;
static const LqnOrder lqn_orders[9] = {
   {2, 1, 1, lqn_mu_s2, lqn_points_s2},
   {4, 2, 3, lqn_mu_s4, lqn_points_s4},
   {6, 3, 6, lqn_mu_s6, lqn_points_s6},
   {8, 4, 10, lqn_mu_s8, lqn_points_s8},
   {10, 5, 15, lqn_mu_s10, lqn_points_s10},
   {12, 6, 21, lqn_mu_s12, lqn_points_s12},
   {14, 7, 28, lqn_mu_s14, lqn_points_s14},
   {16, 8, 36, lqn_mu_s16, lqn_points_s16},
   {18, 9, 45, lqn_mu_s18, lqn_points_s18},
};

// The orders the table carries, for the caller's error message
static const PetscInt lqn_min_order = 2;
static const PetscInt lqn_max_order = 18;

// The table for an order, or NULL if there is none - the caller owns
// the error message, so this says nothing about why
static inline const LqnOrder *lqn_find(PetscInt sn_order)
{
   for (PetscInt k = 0; k < lqn_n_orders; k++) {
      if (lqn_orders[k].sn_order == sn_order) return &lqn_orders[k];
   }
   return NULL;
}

}

#endif
